name: Mulesoft - Deploy

on:
  workflow_dispatch:
    inputs:
      MuleEnvironment:
        type: choice
        description: environment
        options:
        - Sandbox
        required: true
      version:
        description: REL_Version
        required: true

env:
    
    USERNAME: ${{ secrets.USERNAME }}
    PASSWORD: ${{ secrets.PASSWORD }}
    
jobs:
      
   DeploytoMule:
  
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
              java-version: '11'
              distribution: 'adopt'
              
        - name: Version Number
          run: echo "REL_VERSION = ${{ github.event.inputs.version }}"
              
        - name: Deploy to Sandbox
        
          run: |
      
           mvn deploy -DmuleDeploy \
           -DnewVersion=${{github.event.inputs.version}} \
           -Dmule.artifact=$artifactName \
           -Dusername="$USERNAME" \
           -Dpassword="$PASSWORD" \
           -Denvironment= " ${{github.event.inputs.MuleEnvironment}} "
           -Dworkers=1 \
           -Dworker.type=Micro \
           -DskipTests
           
           
           
           
           
          
